#!/usr/bin/env node
// Build step for web/squeeze (node, no dependencies, no network).
//  1. story.json  -> story.js   (window.SQUEEZE_STORY = ...)
//     social.json -> social.js  (window.SQUEEZE_SOCIAL = ... | null when social.json is absent)
//  2. a single-file Artifact bundle at web/dist/squeeze-artifact.html (git-ignored): CSS, JS, data,
//     story and social inlined; no <!doctype>/<html>/<head>/<body> (the Artifact host wraps it);
//     <title> then <style> at the very top; only Google Fonts as an external request; < 16 MB.
// data.json / data.js are owned by the data workflow and only read here.
//
// Usage: node web/squeeze/build-web.mjs [--data path/to/data.json|data.js] [--out path.html] [--no-bundle]
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const REPO_URL = 'https://github.com/vexi-v1/vexi-hakari';
const LINKBASE = REPO_URL + '/blob/main/';
const args = process.argv.slice(2);
const opt = (k) => { const i = args.indexOf(k); return i >= 0 ? args[i + 1] : null; };
const has = (k) => args.includes(k);
const rel = (p) => path.join(HERE, p);
const read = (p) => fs.readFileSync(p, 'utf8');
const exists = (p) => { try { fs.accessSync(p); return true; } catch { return false; } };
const fail = (msg) => { console.error('build-web: ' + msg); process.exit(1); };

// Keep inline <script> content from closing its own tag or opening a comment.
const safeInline = (s) => s.replace(/<\/(script)/gi, '<\\/$1').replace(/<!--/g, '<\\!--');
const jsonToJs = (name, obj) => `window.${name} = ${JSON.stringify(obj)};\n`;

// ---------- 1. story.js and social.js ----------
const storyPath = rel('story.json');
if (!exists(storyPath)) fail('story.json not found next to build-web.mjs');
let story;
try { story = JSON.parse(read(storyPath)); } catch (e) { fail('story.json is not valid JSON: ' + e.message); }
fs.writeFileSync(rel('story.js'), '/* generated by build-web.mjs from story.json; do not edit */\n' + jsonToJs('SQUEEZE_STORY', story));
let social = null;
if (exists(rel('social.json'))) {
  try { social = JSON.parse(read(rel('social.json'))); } catch (e) { fail('social.json is not valid JSON: ' + e.message); }
}
// Errata applied to the page's copy of social.json (social.json itself belongs to the X-sample workflow and is
// not edited here). Each entry is an exact-text replacement inside any string value; once social.json carries
// the corrected wording the entry matches nothing and the build says so, and it can be deleted.
//  The CEO follow is not a "company-side signal": the page says Hims & Hers had no role, and a follow says nothing
//  about involvement (critic finding, 2026-09-26; the 124.70 "top print" wording is already fixed in social.json).
const SOCIAL_ERRATA = [
  ['The only company-side signal is that the Hims & Hers CEO follows the BONER account (first noticed 6 Sep, confirmed 25 Sep).', "A later post noted that the Hims & Hers CEO's personal account follows the BONER account (6 Sep; still following on 25 Sep); a follow says nothing about involvement."],
  ['公司端唯一的訊號，是 Hims & Hers 執行長追蹤了 BONER 帳號（9 月 6 日首次被發現，9 月 25 日確認）。', '之後有貼文指出 Hims & Hers 執行長的個人帳號追蹤了 BONER 帳號（9 月 6 日；9 月 25 日仍在追蹤）；追蹤本身不代表任何參與。']
];
if (social) {
  const hits = SOCIAL_ERRATA.map(() => 0);
  const walk = (v) => {
    if (typeof v === 'string') { let s = v; SOCIAL_ERRATA.forEach(([a, b], k) => { if (s.includes(a)) { s = s.split(a).join(b); hits[k]++; } }); return s; }
    if (Array.isArray(v)) return v.map(walk);
    if (v && typeof v === 'object') { for (const k of Object.keys(v)) v[k] = walk(v[k]); return v; }
    return v;
  };
  social = walk(social);
  const stale = hits.map((n, k) => (n ? null : k + 1)).filter(Boolean);
  console.log(`errata    social: ${hits.reduce((a, b) => a + b, 0)} replacements` + (stale.length ? ` (entries ${stale.join(', ')} matched nothing: social.json may already carry the fix)` : ''));
}
fs.writeFileSync(rel('social.js'), '/* generated by build-web.mjs from social.json (null when absent); do not edit */\n' + jsonToJs('SQUEEZE_SOCIAL', social));
console.log(`story.js  ${story.chapters?.length ?? 0} chapters` + `\nsocial.js ${social ? (social.posts?.length ?? 0) + ' posts' : 'null (no social.json)'}`);
if (has('--no-bundle')) process.exit(0);

// ---------- 2. the Artifact bundle ----------
function loadDataScript() {
  const o = opt('--data');
  const candidates = o ? [path.resolve(o)] : [rel('data.json'), rel('data.js')];
  for (const p of candidates) {
    if (!exists(p)) continue;
    const txt = read(p);
    if (p.endsWith('.json')) { JSON.parse(txt); return { src: p, js: 'window.SQUEEZE_DATA = ' + txt.trim() + ';\n' }; }
    if (!/window\.SQUEEZE_DATA\s*=/.test(txt)) fail(p + ' does not assign window.SQUEEZE_DATA');
    return { src: p, js: txt };
  }
  fail('no data.json or data.js in web/squeeze/ (the data workflow writes them); pass --data <file> to bundle another copy');
}
const data = loadDataScript();
const html = read(rel('index.html'));
const between = (a, b) => {
  const i = html.indexOf(a), j = html.indexOf(b);
  if (i < 0 || j < 0 || j < i) fail(`markers ${a} / ${b} not found in index.html`);
  return html.slice(i + a.length, j).trim();
};
const title = (html.match(/<title>([^<]*)<\/title>/) || [])[1] || 'HIMS Weekend Float Squeeze';
const headLinks = between('<!-- bundle:head-start -->', '<!-- bundle:head-end -->');
let body = between('<!-- bundle:body-start -->', '<!-- bundle:body-end -->');
body = body.replace(/href="\.\.\/index\.html"/g, `href="${REPO_URL}"`);
const scriptList = [...between('<!-- bundle:scripts-start -->', '<!-- bundle:scripts-end -->').matchAll(/<script src="([^"]+)"><\/script>/g)].map((m) => m[1]);
const css = read(rel('squeeze.css'));
const parts = [];
parts.push(`<title>${title}</title>`);
parts.push(`<style>\n${css}\n</style>`);
parts.push(headLinks);
parts.push(body);
parts.push(`<script>window.SQZ_LINKBASE = ${JSON.stringify(LINKBASE)}; window.SQZ_BACK = ${JSON.stringify(REPO_URL)};</script>`);
for (const s of scriptList) {
  let js;
  if (s === 'data.js') js = data.js;
  else if (s === 'story.js') js = read(rel('story.js'));
  else if (s === 'social.js') js = read(rel('social.js'));
  else js = read(rel(s));
  parts.push(`<script>/* ${s} */\n${safeInline(js)}\n</script>`);
}
if (exists(rel('overlay.js'))) parts.splice(parts.length - scriptList.length + scriptList.indexOf('app.js'), 0, `<script>/* overlay.js */\n${safeInline(read(rel('overlay.js')))}\n</script>`);
const out = parts.join('\n') + '\n';

// ---------- checks ----------
const problems = [];
const bytes = Buffer.byteLength(out);
if (bytes > 16 * 1024 * 1024) problems.push(`bundle is ${(bytes / 1048576).toFixed(2)} MB (limit 16 MB)`);
if (/<!doctype/i.test(out)) problems.push('contains <!doctype>');
if (/<html[\s>]/i.test(out) || /<\/html>/i.test(out)) problems.push('contains <html>');
if (/<body[\s>]/i.test(out) || /<\/body>/i.test(out)) problems.push('contains <body>');
if (/<head[\s>]/i.test(out)) problems.push('contains <head>');
const tIdx = out.indexOf('<title>');
if (tIdx !== 0 || out.indexOf('</title>') > 8192) problems.push('<title> is not at the top / within the first 8 KB');
if (out.indexOf('<style>') !== out.indexOf('</title>') + '</title>'.length + 1) problems.push('<style> does not follow <title> directly');
const allowed = ['fonts.googleapis.com', 'fonts.gstatic.com', 'cdnjs.cloudflare.com', 'cdn.jsdelivr.net'];
const requests = [];
for (const m of out.matchAll(/<(script|link|img|iframe|source|video|audio)\b[^>]*\b(src|href)="(https?:)?\/\/([^/"]+)[^"]*"/gi)) {
  const tag = m[1].toLowerCase(), host = m[4];
  if (tag === 'link' && !/rel="(stylesheet|preconnect|preload)"/.test(m[0])) continue;
  requests.push(host);
}
for (const m of out.matchAll(/url\(\s*['"]?(https?:)?\/\/([^/'")]+)/gi)) requests.push(m[2]);
for (const m of out.matchAll(/\.href\s*=\s*'https:\/\/([^/']+)/g)) requests.push(m[1]); // lazily injected stylesheets (Noto Sans TC)
const bad = [...new Set(requests)].filter((h) => !allowed.includes(h));
if (bad.length) problems.push('external requests to non-allowed hosts: ' + bad.join(', '));
if (/<script[^>]+type="module"/i.test(out)) problems.push('contains an ES module script');

fs.mkdirSync(path.join(HERE, '..', 'dist'), { recursive: true });
const outPath = opt('--out') ? path.resolve(opt('--out')) : path.join(HERE, '..', 'dist', 'squeeze-artifact.html');
if (problems.length) { console.error('bundle checks failed:\n - ' + problems.join('\n - ')); process.exit(1); }
fs.writeFileSync(outPath, out);
console.log(`bundle    ${path.relative(process.cwd(), outPath)}  ${(bytes / 1048576).toFixed(2)} MB  title@${tIdx}  data from ${path.relative(HERE, data.src) || data.src}`);
console.log(`checks    ok (no doctype/html/head/body, title+style first, hosts: ${[...new Set(requests)].join(', ') || 'none'})`);
